Add BoolVal to validation rules
shucream0117/phalcon-libs pull request #24
Opened 2022-08-28 09:34 UTC by yonex

- クエリストリングから true, false を受け取る際に BoolVal ルールがほしくなったので追加しました
- BoolVal と BoolType のテストを追加しました

2022-08-28 09:46 UTC, yonex commented on tests/Unit/Validators/CustomRules/BoolTypeTest.php
> +        };
AbstractValidatorTest を参考にしました

2022-08-28 18:22 UTC, shucream0117 requested changes

2022-08-28 18:22 UTC, shucream0117 commented on src/Validators/CustomRules/BoolVal.php
> +        return $value === 'true' || $value === 'false';
- $value が bool値の場合
- 大文字(TRUE)や入り混じっている場合(True)

とかもあるので、そのあたりも考慮されるとありがたい

2022-08-29 01:57 UTC, yonex commented on src/Validators/CustomRules/BoolVal.php
> +        return $value === 'true' || $value === 'false';
いずれも checkValue() としては true を返したいということですよね？考慮します

2022-08-29 02:07 UTC, yonex commented on tests/Unit/Validators/CustomRules/BoolValTest.php
> +        $this->assertSame('falSE', $validationResult->validated('is_something'));
考慮しましたが、割と validated() が使いづらい印象になりました。
使うときは validated() を呼び出す側で注意するということでよいでしょうか？

2022-08-31 09:48 UTC, shucream0117 commented on tests/Unit/Validators/CustomRules/BoolValTest.php
> +        $this->assertSame('falSE', $validationResult->validated('is_something'));
> 使うときは validated() を呼び出す側で注意するということでよいでしょうか？

まぁ、そうですね 🤔  仕方ない感

2022-08-31 09:48 UTC, shucream0117 approved these changes

2022-08-31 09:48 UTC, merged